trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'wouterbau'
    scannerMode: 'MSBuild'
    projectKey: 'WouterBau_ShadowRoller'
    projectName: 'ShadowRoller'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/coverage.opencover.xml"
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    publishTestResults: true
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat="json%2ccobertura%2copencover" /p:CoverletOutput="../coverage/" /p:MergeWith="../coverage/coverage.json" /p:SkipAutoProps=true -m:1'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-stryker'
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools

- task: DotNetCoreCLI@2
  displayName: 'Execute dotnet-stryker'
  inputs:
    command: custom
    custom: stryker
    arguments: -s .\ShadowRoller.sln

- task: PublishMutationReport@1
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: '**/mutation-report.html'