trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    publishTestResults: true
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat="json%2ccobertura" /p:CoverletOutput="../coverage/" /p:MergeWith="../coverage/coverage.json" /p:SkipAutoProps=true -m:1'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'